apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: octoprint
  name: octoprint
spec:
  replicas: 1
  selector:
    matchLabels:
      run: octoprint
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: octoprint
    spec:
      containers:
      - image: octoprint/octoprint
        name: octoprint
        resources: {}
status: {}