---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: octoprint
  namespace: flux-system
spec:
  chart:
    spec:
      chart: octoprint-chart
      sourceRef:
        kind: HelmRepository
        name: octoprint-chart
  interval: 10m0s

