---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: check-sops-secrets
        name: check for unencrypted SOPS secretes
        entry: ./hack/check-sops-secrets-hook.sh
        language: script
        files: \.(ya?ml)$
