helmOperator:
  create: false
git:
  url: "git@github.com:mcclaren00/home-k3s-cluster.git"
  branch: master
  path: cluster/deployments
image:
  repository: raspbernetes/flux
  tag: 1.20.2
registry:
  rps: 1
  bursts: 1
memcached: 
  enabled: true
syncGarbageCollection: 
  enabled: true
  dry: false 
# TODO: install prometheus-operator
