---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: octoprint
  namespace: flux-system
spec:
  interval: 20m0s
  ref:
    branch: master
  url: https://github.com/OctoPrint/OctoPrint.git

