---

- name: copy k3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755

- name: enable k3s service
  systemd:
    name: k3s-node
    daemon-reload: yes
    state: restarted
    enabled: yes